WebappHelp/src/main/java/se/esss/ics/help/LoginController.java
/*
 * Copyright (c) 2014 European Spallation Source
 * Copyright (c) 2014 Cosylab d.d.
 *
 * This file is part of Cable Database.
 * Cable Database is free software: you can redistribute it and/or modify it
 * under the terms of the GNU General Public License as published by the Free
 * Software Foundation, either version 2 of the License, or any newer version.
 * 
 * This program is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or
 * FITNESS FOR A PARTICULAR PURPOSE.  See the GNU General Public License for
 * more details.
 *
 * You should have received a copy of the GNU General Public License along with
 * this program. If not, see https://www.gnu.org/licenses/gpl-2.0.txt
 */
package se.esss.ics.help;

import java.io.Serializable;

import javax.faces.application.FacesMessage;
import javax.faces.application.FacesMessage.Severity;
import javax.faces.bean.ManagedBean;
import javax.faces.bean.ViewScoped;
import javax.faces.context.FacesContext;
import javax.inject.Inject;

import org.primefaces.context.RequestContext;

import se.esss.ics.rbac.loginmodules.service.Message;
import se.esss.ics.rbac.loginmodules.service.RBACSSOSessionService;

/**
 * A UI controller bean for the login / logout button and form.
 *
 * @author <a href="mailto:miha.novak@cosylab.com">Miha Novak</a>
 */
@ManagedBean
@ViewScoped
public class LoginController implements Serializable {

    private static final long serialVersionUID = 5984791196886929176L;
    
    @Inject
    private RBACSSOSessionService sessionService;

    private String username;
    private char[] password;
    
    /** Opens login dialog. */
    public void openLoginDialog() {
    	RequestContext.getCurrentInstance().execute("PF('loginDialog').show()");
    }

    /** Performs login. */
    public void login() {
        try {
            final Message result = sessionService.login(username, new String(password));
            showMessage(result, "Sign In");
        } finally {
            clearPassword();
        }
    }

    /** Performs logout. */
    public void logout() {
        try {
            final Message result = sessionService.logout();
            showMessage(result, "Sign Out");
        } finally {
            clearPassword();
        }
    }

    /** Cancels login in progress. */
    public void cancel() {
        clearPassword();
    }

    /** @return the username */
    public String getUsername() {
        return username;
    }

    /** @param username the username to set */
    public void setUsername(String username) {
        this.username = username;
    }

    /** @return the password */
    public char[] getPassword() {
        return password;
    }

    /** @param password the password to set */
    public void setPassword(char[] password) {
        this.password = password;
    }
    
    /**
     * @return true if user is logged in otherwise false.
     */
    public boolean isLoggedIn() {
    	return sessionService.isLoggedIn();
    }
    
    /**
     * Returns the welcome message. Welcome message depends on whether a user is logged in.
     * 
     * @return the welcome message.
     */
    public String getWelcomeMessage() {
        if (!sessionService.isLoggedIn()) {
            return "Welcome, unknown visitor.";
        } else {
            return "Welcome, " + sessionService.getVisibleName() + ".";
        }
    }

    /**
     * Shows message.
     * 
     * @param result result
     * @param action action
     */
    private void showMessage(Message result, String action) {
        final Severity severity = result.isSuccessful() ? FacesMessage.SEVERITY_INFO : FacesMessage.SEVERITY_ERROR;
        final String summary = action + " " + (result.isSuccessful() ? "Succeeded" : "Failed");
        final String message = result.getMessage();
        final FacesContext context = FacesContext.getCurrentInstance();
        context.addMessage(null, new FacesMessage(severity, summary, message));
    }
    
    /**
     * Clears password.
     */
    private void clearPassword() {
        password = null;
    }
}

WebappHelp/src/main/webapp/WEB-INF/includes/api-manual.xhtml
<?xml version='1.0' encoding='UTF-8' ?>
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<ui:composition xmlns:ui="http://java.sun.com/jsf/facelets"
    template="../templates/help.xhtml"
    xmlns:h="http://java.sun.com/jsf/html"
    xmlns:f="http://java.sun.com/jsf/core"
    xmlns:p="http://primefaces.org/ui"
    xmlns:fc="http://java.sun.com/jsf/composite/comps">

    <ui:define name="title">Naming Tool API Manual</ui:define>

    <ui:define name="content">
        <h:form>
            <p:panelGrid id="helpPanelGrid" styleClass="noBorderPanelgrid">
                <p:row>
                    <p:column>

                        <ui:param name="restRoot"
                            value="#{request.scheme}://#{request.serverName}:#{request.serverPort}#{request.contextPath}/rest" />

                        <div style="text-align: left">

                            <h2>API Manual</h2>
                            <p>
                                Data in the Naming Service can be accessed programmatically
                                through a <a
                                    href="http://en.wikipedia.org/wiki/Representational_state_transfer"
                                    target="_blank">RESTful</a> Application Programming Interface
                                (API). The Naming System API follows <a
                                    href="http://semver.org/" target="_blank">Semantic
                                    Versioning</a> for its version numbers. The current API version
                                number is #{msgs.apiversion}.
                            </p>

                            <h3>Representations</h3>
                            <p>
                                The representations of the resources must be specified through
                                HTTP ACCEPT header. This API supports JSON and XML
                                representations. Examples:
                                <ul>
                                    <li>Accept: application/json</li>
                                    <li>Accept: application/xml</li>
                                </ul>
                            </p>
                            <h3>Base URL</h3>
                                <p>
                                The base URL for Resource Identifiers is #{restRoot}.
                                </p>
                            <h3>Resources</h3>
                            <p>
                            <p:panelGrid style="text-align: left">
                                <f:facet name="header">
                                    <p:row>
                                        <p:column>Name</p:column>
                                        <p:column>Method</p:column>
                                        <p:column>Resource ID</p:column>
                                        <p:column>Description</p:column>
                                        <p:column>Example</p:column>
                                    </p:row>
                                </f:facet>
                                <p:row>
                                    <p:column>All Device Names</p:column>
                                    <p:column>GET</p:column>
                                    <p:column>/deviceNames</p:column>
                                    <p:column>List of all device names</p:column>
                                    <p:column>#{restRoot}/deviceNames</p:column>
                                </p:row>
                                <p:row>
                                    <p:column>Device Name With UUID</p:column>
                                    <p:column>GET</p:column>
                                    <p:column>/deviceNames/{uuid}</p:column>
                                    <p:column>Information of device name for given UUID. </p:column>
                                    <p:column>#{restRoot}/deviceNames/354fc899-add8-494c-a62e-1250837e1135</p:column>
                                </p:row>
                            </p:panelGrid>
                            </p>        
                        </div>
                    </p:column>
                </p:row>
            </p:panelGrid>
        </h:form>
    </ui:define>

</ui:composition>

WebappHelp/src/main/webapp/banner.xhtml
<ui:composition xmlns:ui="http://java.sun.com/jsf/facelets"
    xmlns:f="http://java.sun.com/jsf/core"
    xmlns:h="http://java.sun.com/jsf/html"
    xmlns:p="http://primefaces.org/ui">
    <h:form>
        <h:panelGrid styleClass="bannerGrid" columns="3" columnClasses="bannerImage,bannerNavigationColumn,bannerLoginColumn">
            <h:panelGroup layout="block">
                <a class="bannerLink" href="http://europeanspallationsource.se">
                    <h:graphicImage value="/resources/images/logo-white.png" />
                </a>
            </h:panelGroup>
            <h:panelGroup layout="block">
                <p:menubar styleClass="bannerNavigation">
                    <p:menuitem value="Home" url="/index.xhtml" styleClass="bannerNavigationButton" />
                </p:menubar>
            </h:panelGroup>
            <h:panelGroup id="loginInfoPanel" layout="block">
				<p:outputLabel value="#{loginController.welcomeMessage}" styleClass="bannerMarginText"/>
				<p:commandButton id="bannerLoginButton" value="Sign In" rendered="#{!loginController.loggedIn}" action="#{loginController.openLoginDialog()}" update="loginInfoPanel" styleClass="bannerButton"/>
				<p:commandButton id="bannerLogoutButton" value="Sign Out" rendered="#{loginController.loggedIn}" action="#{loginController.logout()}" update=":siteContainer" styleClass="bannerButton" />
			</h:panelGroup>
        </h:panelGrid>
    </h:form>
    <p:dialog header="Sign In" closeOnEscape="true" modal="true" resizable="false" showEffect="fade" hideEffect="fade" widgetVar="loginDialog">
		<ui:include src="login-dialog.xhtml"/>
	</p:dialog>
</ui:composition>

WebappHelp/src/main/webapp/cable/adding-new-cable-types-to-approved-cable-types-list.xhtml
<ui:composition template="../templates/help.xhtml"
    xmlns:ui="http://java.sun.com/jsf/facelets"
    xmlns:f="http://java.sun.com/jsf/core"
    xmlns:h="http://java.sun.com/jsf/html"
    xmlns:p="http://primefaces.org/ui">

    <ui:define name="title">Adding new cable types to Approved Cable Types list</ui:define>

    <ui:define name="content">
        <h:form>
            <p:panelGrid id="helpPanelGrid" styleClass="noBorderPanelgrid">
                <p:row>
                    <p:column>
                        <h2 style="margin-top: -1px; margin-bottom: 1px">Adding new
                            cable types to Approved Cable Types list</h2>
                        <p>This workflow describes the steps to register new cable
                            types that are approved to be uploaded by users into the CD.</p>
                        <ol>
                            <li><p>
                                    Go to the <a
                                        href="https://ess-ics.atlassian.net/wiki/display/ID/ICS+Software+Catalog">ICS
                                        Software Catalog</a> and navigate to <a
                                        href="https://cable.esss.lu.se/">Cable Database (CD)</a>.
                                    Login to the application using your LDAP credentials and from
                                    the menu navigate to <i>CABLE TYPES</i> view. Select <i>IMPORT
                                        APPROVED CABLE TYPES LIST...</i> and download the example Cable
                                    Type spreadsheet.
                                </p> <h:graphicImage library="images/cable" name="5.1.1.jpg"
                                    styleClass="resize" /></li>
                            <li><p>Enter new approved cable types into the
                                    spreadsheet.</p>
                                <p>The example spreadsheet is already populated with some
                                    example data. In the spreadsheet, each row represents one
                                    approved cable type, while the columns define the cable type
                                    attributes.</p> <h:graphicImage library="images/cable"
                                    name="5.1.2.jpg" styleClass="resize" />
                                <p>
                                    The first column specifies the import operation for the cable
                                    type defined in this row, and can be either <i>UPDATE</i>
                                    (default, adding/updating cable types) or <i>DELETE</i>
                                    (deleting cable types). For the initial import the default is
                                    used.
                                </p>
                                <p>
                                    The rest of the columns contain user entered cable type
                                    attributes. The mandatory attributes are marked with <i>*</i>.
                                </p>
                                <p>
                                    The <b>Cable Obsolete</b> column is not user editable and
                                    describes the whether this cable type was entered into the
                                    database, but then made obsolete.
                                </p>
                                <p>The mandatory user editable cable attributes are the
                                    following:</p>
                                <ul>
                                    <li><p>
                                            <b>Name</b> (String) - Cable Type name/code. This should be a
                                            short uppercase mnemonic that is unique. It must not contain
                                            slash characters (/).
                                        </p></li>
                                    <li><p>
                                            <b>Raceway</b> (Fixed enumeration) - The raceway types
                                            allowed for this cable type for the purpose of cable routing.
                                            Can be set to <i>NONE</i>, <i>CONDUIT ONLY</i>, <i>TRAY
                                                OR CONDUIT</i>, <i>RISER OR TRAY OR CONDUIT</i>, or <i>CUSTOM</i>.
                                        </p></li>
                                    <li><p>
                                            <b>Request#, Revision, Date</b> - Version information for
                                            this cable type. This is specified when adding the cable type
                                            for the first time and cannot be modified.
                                        </p>
                                        <ul>
                                            <li><p>
                                                    <b>Request#</b> (String) - The number of the request for
                                                    this cable type.
                                                </p></li>
                                            <li><p>
                                                    <b>Revision</b> (String) - The revision of the current
                                                    data.
                                                </p></li>
                                            <li><p>
                                                    <b>Date</b> (Date) - The date the cable type was requested.
                                                </p></li>
                                        </ul></li>
                                </ul>
                                <p>Optional cable type attributes do not need to be defined,
                                    and can be defined at a later point after the import. They are
                                    the following:</p>
                                <ul>
                                    <li><p>
                                            <b>Characteristics</b> (String) - Freeform text entry of
                                            cable type key characteristics. This can include keywords and
                                            tags to search by.
                                        </p></li>
                                    <li><p>
                                            <b>Service</b> (String) - Cable type service or function
                                            description.
                                        </p></li>
                                    <li><p>
                                            <b>Voltage</b> (String) - Cable type voltage rating. This can
                                            be an arbitrary string, but should contain meaningful groups.
                                            Open the drop down filter for this column in CD for a list of
                                            existing distinct values.
                                        </p></li>
                                    <li><p>
                                            <b>Insulation</b> (String) - Cable type insulation material.
                                            This can be an arbitrary string, but should contain
                                            meaningful groups. Open the drop down filter for this column
                                            in CD for a list of existing distinct values.
                                        </p></li>
                                    <li><p>
                                            <b>Jacket</b> (String) - Cable type jacket. This can be an
                                            arbitrary string, but should contain meaningful groups. Open
                                            the drop down filter for this column in CD for a list of
                                            existing distinct values.
                                        </p></li>
                                    <li><p>
                                            <b>Flammability</b> (String) - Cable type flammability
                                            classification. This can be an arbitrary string, but should
                                            contain meaningful groups. Open the drop down filter for this
                                            column in CD for a list of existing distinct values.
                                        </p></li>
                                    <li><p>
                                            <b>TID</b> (Numeric) - Total ionizing dose for the cable type
                                            (Mrad).
                                        </p></li>
                                    <li><p>
                                            <b>Weight</b> (Numeric) - Weight of the cable (kg per meter).
                                        </p></li>
                                    <li><p>
                                            <b>Diameter</b> (Numeric) - Outer diameter of the cable type
                                            (mm).
                                        </p></li>
                                    <li><p>
                                            <b>Specification</b> (URL) - Reference to the ESS
                                            specification document in the document repository. This
                                            specification is in use when the exact cable type and
                                            manufacturer are not known yet. There is a template document
                                            available that can be filled out for this purpose.
                                        </p></li>
                                    <li><p>
                                            <b>Model</b> (URL) - An URL to manufacturer and model
                                            document. Here an arbitrary link to a location or document
                                            where the information on manufacturer and cable type model is
                                            described. It is suggested that the link points to document
                                            copies stored in ESS document repository, as external links
                                            can change or become inaccessible.
                                        </p></li>
                                    <li><p>
                                            <b>Comments</b> (String) - Comment for the cable type. This
                                            can be arbitrary text.
                                        </p></li>
                                </ul></li>
                            <li>
                                <p>Import the Approved Cable Type spreadsheet.</p>
                                <p>
                                    Select <i>CHOOSE</i> in the upload dialog and navigate to the
                                    filled in spreadsheet file. Open it and select <i>UPLOAD</i>.
                                    After the spreadsheet is uploaded, the application displays a
                                    list of modifications that will be performed at import. If
                                    there are any issues with the data, an error will be reported
                                    detailing the issue. In this case, the error must be corrected
                                    on the request spreadsheet and the spreadsheet re-uploaded.
                                    When the whole spreadsheet is valid, the approved cable types
                                    can be imported into CD.
                                </p>
                            </li>
                        </ol>
                    </p:column>
                </p:row>
            </p:panelGrid>
        </h:form>
    </ui:define>
</ui:composition>

WebappHelp/src/main/webapp/cable/deleting-cables.xhtml
<ui:composition template="../templates/help.xhtml"
    xmlns:ui="http://java.sun.com/jsf/facelets"
    xmlns:f="http://java.sun.com/jsf/core"
    xmlns:h="http://java.sun.com/jsf/html"
    xmlns:p="http://primefaces.org/ui">

    <ui:define name="title">Deleting cables</ui:define>

    <ui:define name="content">
        <h:form>
            <p:panelGrid id="helpPanelGrid" styleClass="noBorderPanelgrid">
                <p:row>
                    <p:column>
                        <h2 style="margin-top: -1px; margin-bottom: 1px">Deleting
                            cables</h2>
                        <p>
                            This workflow describes the steps to delete the cables present in
                            the <a href="https://cable.esss.lu.se/">Cable Database (CD)</a>.
                            This is used for example when the imported cables will not be
                            used, or when they will be replaced with other cables of
                            different type or connecting different endpoints.
                        </p>
                        <ol>
                            <li><p>
                                    Export cables to delete as described on the <a
                                        href="spreadsheet-data-exports.xhtml">spreadsheet data
                                        exports page</a>.
                                </p></li>
                            <li><p>
                                    Change the import operation in the first row of the cables from
                                    <i>UPDATE</i> to <i>DELETE</i>.
                                </p></li>
                            <li>
                                <p>Optionally, add the replacement cables.</p>
                                <p>
                                    The replacement cables can be added to the same spreadsheet,
                                    with import operation <i>UPDATE</i> and without assigned cable
                                    number. These cables will be added as new.
                                </p> <h:graphicImage library="images/cable" name="4.4.1.jpg"
                                    styleClass="resize" />
                            </li>
                            <li><p>Upload the spreadsheet.</p>
                                <p>
                                    After the spreadsheet is uploaded, the CD displays the
                                    information on which cables are to be deleted. Select <i>IMPORT</i>
                                    to confirm the delete operation.
                                </p> <h:graphicImage library="images/cable" name="4.4.2.jpg"
                                    styleClass="resize" /></li>
                        </ol>
                    </p:column>
                </p:row>
            </p:panelGrid>
        </h:form>
    </ui:define>
</ui:composition>

WebappHelp/src/main/webapp/cable/obsoleting-cables-on-the-approved-cable-list.xhtml
<ui:composition template="../templates/help.xhtml"
    xmlns:ui="http://java.sun.com/jsf/facelets"
    xmlns:f="http://java.sun.com/jsf/core"
    xmlns:h="http://java.sun.com/jsf/html"
    xmlns:p="http://primefaces.org/ui">

    <ui:define name="title">Obsoleting cables on the approved cable list</ui:define>

    <ui:define name="content">
        <h:form>
            <p:panelGrid id="helpPanelGrid" styleClass="noBorderPanelgrid">
                <p:row>
                    <p:column>
                        <h2 style="margin-top: -1px; margin-bottom: 1px">Obsoleting
                            cables on the approved cable list</h2>
                        <p>This workflow describes the steps to make an approved cable
                            type obsolete. After a cable type is obsolete, new cables of this
                            type cannot be imported. Old cables of this type are unaffected,
                            and can be replaced with new cables as appropriate.</p>
                        <ol>
                            <li><p>Export the list of approved cable types.</p> <h:graphicImage
                                    library="images/cable" name="5.2.1.jpg" styleClass="resize" /></li>
                            <li>
                                <p>
                                    In the spreadsheet, change the import operation in the first
                                    row of the cable types to obsolete from <i>UPDATE</i> to <i>DELETE</i>.
                                </p> <h:graphicImage library="images/cable" name="5.2.2.jpg"
                                    styleClass="resize" />
                            </li>
                            <li><p>Import the cable type spreadsheet to the CD and
                                    confirm the deletion.</p>
                                <p>
                                    By default, the cable types that were obsoleted are not visible
                                    in the <i>CABLE TYPES</i> view. To include obsoleted cables in
                                    the view, use the Show Cable Types filter.
                                </p> <h:graphicImage library="images/cable" name="5.2.3.jpg"
                                    styleClass="resize" /></li>
                        </ol>
                    </p:column>
                </p:row>
            </p:panelGrid>
        </h:form>
    </ui:define>
</ui:composition>

WebappHelp/src/main/webapp/cable/restoring-cable-type-for-use.xhtml
<ui:composition template="../templates/help.xhtml"
    xmlns:ui="http://java.sun.com/jsf/facelets"
    xmlns:f="http://java.sun.com/jsf/core"
    xmlns:h="http://java.sun.com/jsf/html"
    xmlns:p="http://primefaces.org/ui">

    <ui:define name="title">Restoring cable type for use</ui:define>

    <ui:define name="content">
        <h:form>
            <p:panelGrid id="helpPanelGrid" styleClass="noBorderPanelgrid">
                <p:row>
                    <p:column>
                        <h2 style="margin-top: -1px; margin-bottom: 1px">Restoring
                            cable type for use</h2>
                        <p>
                            As with the cable instances, the obsoleted cable types can be
                            restored for use, but with a new <b>Name/Code</b>. This can be
                            achieved by exporting the obsoleted cable type, updating the <b>Name/Code</b>
                            and the version information <b>(Request#, Revision, Date)</b>.
                            Cables of the old types have to be reimported with the new types
                            as well.
                        </p>
                    </p:column>
                </p:row>
            </p:panelGrid>
        </h:form>
    </ui:define>
</ui:composition>

WebappHelp/src/main/webapp/templates/help.xhtml
<?xml version="1.0" encoding="UTF-8" ?>
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml"
    xmlns:f="http://java.sun.com/jsf/core"
    xmlns:h="http://java.sun.com/jsf/html"
    xmlns:ui="http://java.sun.com/jsf/facelets"
    xmlns:p="http://primefaces.org/ui">
    <h:head>
        <meta content='text/html; charset=UTF-8' http-equiv="Content-Type"/>
        <title><ui:insert name="title">RBAC Help</ui:insert></title>
        <link rel="shortcut icon" href="../resources/images/favicon.ico" type="image/vnd.microsoft.icon" />            
    </h:head>
    <h:body id="body">
        <h:outputStylesheet name="default.css" library="css" />
        <h:panelGroup id="siteContainer" class="container" layout="block">
            <h:panelGroup id="siteBanner">
            	<h:panelGroup class="banner" layout="block">
                	<ui:include src="../banner.xhtml" />
                </h:panelGroup>
                <h:panelGroup rendered="#{!loginController.loggedIn}">
                	<center><h1>You are not authorised to view this page. Please log in.</h1></center>
                </h:panelGroup>
            </h:panelGroup>
            <h:panelGroup class="navigation" layout="block" rendered="#{loginController.loggedIn}">
                <ui:include src="../navigation/help-navigation.xhtml" />
            </h:panelGroup>
            <h:panelGroup id="siteContent" class="content" layout="block" rendered="#{loginController.loggedIn}">
                <p:growl id="siteContainerGrowl" showDetail="true" life="4000" />
                <ui:insert name="content"></ui:insert>
            </h:panelGroup>
        </h:panelGroup>
    </h:body>
</html>